name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:
       branches:
        - master
    

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: hclasmn/yacd:test
jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.


    runs-on: ubuntu-latest
#    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login  -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image
        run: docker push $IMAGE_NAME
        
      - name: chmod
        run: chmod 777 ./build.sh
      - name: buildx
        run: ./build.sh
